### ISSUE TITLE
Install impossible on a web server

### ISSUE THREAD

**Issue by wbaridon** [ranisalt/node-argon2#148]
- [x] Checkout to the latest version, **including submodules**
- [x] Try to find an *isolated* way to reproduce the behavior
- [x] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1. I use a planethoster web hosting offer
2. I try to do a npm install but the install failed 

### Expected behaviour
The install need to work

### Actual behaviour
Error output and impossible to install 

### Environment
**Node version:**
8.11 

I have this log on the web server and no problem for localhost. 

```
make: Entering directory `/home/project/nodevenv/api/8/lib/node_modules/argon2/build'
  CC(target) Release/obj.target/libargon2/argon2/src/opt.o
  CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
  CC(target) Release/obj.target/libargon2/argon2/src/core.o
  CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/libargon2/argon2/src/thread.o
  CC(target) Release/obj.target/libargon2/argon2/src/encoding.o
  AR(target) Release/obj.target/argon2.a
  COPY Release/argon2.a
  CXX(target) Release/obj.target/argon2/src/argon2_node.o
../src/argon2_node.cpp:6:17: fatal error: nan.h: No such file or directory
 #include <nan.h>
                 ^
compilation terminated.
make: *** [Release/obj.target/argon2/src/argon2_node.o] Error 1
make: Leaving directory `/home/project/nodevenv/api/8/lib/node_modules/argon2/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/alt/alt-nodejs8/root/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.10.0-714.10.2.lve1.5.19.7.el7.x86_64
gyp ERR! command "/opt/alt/alt-nodejs8/root/usr/bin/node" "/opt/alt/alt-nodejs8/root/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/project/nodevenv/api/8/lib/node_modules/argon2
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN project-api@0.0.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.19.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the argon2@0.19.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/project/.npm/_logs/2018-10-22T12_18_43_683Z-debug.log
```

**Comment by ranisalt** [comment]
Your server is not installing dependencies. I can see `nan`, a dependency specified on package.json, is missing.
