### ISSUE TITLE
mac install not working

### ISSUE THREAD

**Issue by tmackness** [ranisalt/node-argon2#171]
Trying to install on macOS unsuccessfully. 

### Environment
**Operating system**:
macOS mojave

**Node version:** 
10.15.0

**Compiler version:**
node-gyp -v v3.8.0

gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.3)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

brew info gcc
gcc: stable 8.3.0

I found my version **g++-8** in `/usr/local/bin`.

After running `CXX=g++-8 npm install argon2`

I get this errors:

```bash
> argon2@0.21.0 install /Users/tm/Dropbox/app/node_modules/argon2
> node-gyp rebuild

  CC(target) Release/obj.target/libargon2/argon2/src/opt.o
  CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
  CC(target) Release/obj.target/libargon2/argon2/src/core.o
  CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/libargon2/argon2/src/thread.o
  CC(target) Release/obj.target/libargon2/argon2/src/encoding.o
  LIBTOOL-STATIC Release/argon2.a
  CXX(target) Release/obj.target/argon2/src/argon2_node.o
g++-8: error: v2/ExpressJS/backend/app/node_modules/node-addon-api: No such file or directory
g++-8: error: unrecognized command line option '-stdlib=libc++'
make: *** [Release/obj.target/argon2/src/argon2_node.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/tm/Dropbox/app/node_modules/argon2
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.21.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the argon2@0.21.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tm/.npm/_logs/2019-04-05T07_27_30_384Z-debug.log
```

Any help thanks

**Comment by tmackness** [comment]
Disregard, my issue was solved when I removed a space in my path (not seen above). Also on mac it might help using clang from what I could read

e.g. 
```
brew install llvm
CXX=clang++ npm install argon2
```
