### ISSUE TITLE
Version 0.22.0 Windows Build Broken

### ISSUE THREAD

**Issue by SpudNyk** [ranisalt/node-argon2#174]
Welcome to the issues section if it's your first time!

### Before creating an issue, please be sure to:
- [x] Checkout to the latest version, **including submodules**
- [x] Try to find an *isolated* way to reproduce the behavior
- [x] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1. Try to build on windows

### Expected behaviour
Should build correctly on windows

### Actual behaviour
Fails with the below

```
\node_modules\argon2\src\argon2_node.cpp(82): error C2440: 'initializing': cannot convert from 'char *' to 'uint8_t *' [C:\...\argontest\node_modules\argon2\build\argon2.vcxproj]
  c:\...\argontest\node_modules\argon2\src\argon2_node.cpp(82): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\...\argontest\node_modules\argon2
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
```

### Environment
**Operating system**:
Windows 10
**Node version:**
Node 10.15.3

**Compiler version:**
MS 2017

When I changed line 82 in `src\argon2_node.cpp` to read
```
        uint8_t* buf = reinterpret_cast<uint8_t*>(new char[opts.hash_length]);
```

That fixed it and running the test script passed

**Comment by Orel-A** [comment]
same issue here

**Comment by joelmeaders** [comment]
I also have this issue.

**Comment by usamamashkoor** [comment]
Same issue here.

**Comment by ranisalt** [comment]
0.22.1 will be released with a fix soon.
