### ISSUE TITLE
TypeError: Cannot destructure property `ok` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by jocafi** [ranisalt/node-argon2#179]
I had to downgrade the library to 0.21.0 in order it could work.

### Steps to reproduce
1. Create the test.js:

```
var crypto = require('argon2');

var password = 'monkey';

async function createHash() {
  try {
    var hash = await crypto.hash(password).then(passwordDigest => {
      console.log("The result of hashing " + password + " is:\n\n" + passwordDigest + "\n\n");
    }).catch(reason => console.error("Error generating password hash: " + reason))

  } catch (e) {

  }
}

createHash();
```

2. Execute the script:  $ node test.js

### Expected behaviour
hashed password  is expected.

### Actual behaviour
I receive the error:
```
const { ok } = require('assert').strict
                                ^
TypeError: Cannot destructure property `ok` of 'undefined' or 'null'.
    at Object.<anonymous> (/security-studies/node_modules/argon2/argon2.js:2:33)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/security-studies/server/database.ts:5:1)
    at Module._compile (module.js:653:30)
```

### Environment
**Operating system**:
MacOS  (Mojave)

**Node version:**
8.12.0

**Compiler version:**

**Comment by ranisalt** [comment]
v0.23.0 should fix. Please reopen if not.
