### ISSUE TITLE
support node-pre-gyp

### ISSUE THREAD

**Issue by zuohuadong** [ranisalt/node-argon2#195]
Welcome to the issues section if it's your first time!

### Before creating an issue, please be sure to:
- [x] Checkout to the latest version, **including submodules**
- [x] Try to find an *isolated* way to reproduce the behavior
- [x] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1.  npm i -g @zeit/ncc
2.  ncc run xxx.js
3. error

### Expected behaviour

like grpc: 
![image](https://user-images.githubusercontent.com/11203929/62098742-35f09380-b2be-11e9-8af3-f5eedf777001.png)

https://github.com/mapbox/node-pre-gyp

### Actual behaviour

```
/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:201473
  throw new Error('No native build was found for ' + target)
  ^

Error: No native build was found for platform=darwin arch=x64 runtime=node abi=72 uv=1 libc=glibc
    at Function.module.exports.load.path (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:201473:9)
    at load (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:201437:30)
    at Object.<anonymous> (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:217784:81)
    at webpack_require (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:22:30)
    at Object.<anonymous> (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:259301:18)
    at webpack_require (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:22:30)
    at Object.<anonymous> (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:411873:10)
    at webpack_require (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:22:30)
    at Object.<anonymous> (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:210789:17)
    at webpack_require (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:22:30)
    at startup (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:39:19)
    at /Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:45:18
    at Object.<anonymous> (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:48:10)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
```

### Environment
**Operating system**:
ubuntu 18.04
**Node version:**
12.7.0
**Compiler version:**
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

**Comment by ranisalt** [comment]
Feel free to open a PR if you can fix this.

Node's ecosystem for native addons is ridiculously awful (node-gyp being based on a tool so deprecated it's successor was already deprecated too). I don't have the time to plumb this down, I already wanted to move away from node-gyp for a while but it is so unnecessarily hard.
