### ISSUE TITLE
npm install requires nan to be installed first

### ISSUE THREAD

**Issue by michaelkane** [ranisalt/node-argon2#2]
When I try `npm install argon2` I'm getting:
```
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:55:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:399:26)
    at node.js:592:27
    at nextTickCallbackWith0Args (node.js:433:9)
gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
```

However if I `npm install nan` first it works fine.

**Comment by ranisalt** [comment]
It's strange, because nan is listed as dependency on [package.json](https://github.com/ranisalt/node-argon2/blob/2149db785df3eeac4bc7de18e3fae719560ba8fd/package.json).

Maybe the preinstall hook, which needs nan, is being executed before installing all packages and not only node-argon2, I'll have a look.

**Comment by ranisalt** [comment]
Could you check if 60d8ed2 fixes? I moved rebuilding to `postinstall` instead of `preinstall`.

**Comment by ranisalt** [comment]
v0.4.1 should do the trick.

**Comment by michaelkane** [comment]
Ah yes, that works perfectly.  Thanks!
