### ISSUE TITLE
Not working on Windows / VS 2019

### ISSUE THREAD

**Issue by acceleratxr** [ranisalt/node-argon2#205]
When trying to add or install as a dependency on Windows with Visual Studio 2019 installed I get the following errors.

```
Exit code: 7
Command: node-gyp-build
Arguments:
Directory: ...\node_modules\argon2
Output:
...\node_modules\argon2>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.16.1 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   '...\\node_modules\\argon2\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '...\\.node-gyp\\10.16.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=...\\.node-gyp\\10.16.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=...\\.node-gyp\\10.16.1\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=...\\node_modules\\argon2',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   '...\\node_modules\\argon2\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd ...\node_modules\argon2
gyp ERR! node -v v10.16.1
gyp ERR! node-gyp -v v3.8.0
```

**Comment by hoangvvo** [comment]
https://github.com/nodejs/node-gyp/issues/1753

**Comment by erikyuzwa** [comment]
affected by this as well. Can't find an older VS community version as you now need a Visual Studio subscription (yes, even for Community editions it seems). Thanks Microsoft.

My only workaround was to uninstall VS2019 and dig out my old VS2010 install media.

**Comment by hoangvvo** [comment]
@erikyuzwa refers to my previous comment, I tried it and can confirm that the workaround does work on Windows (10).

**Comment by erikyuzwa** [comment]
Thanks @hoangvvo - I shall try that. :bow:

**Comment by jeffrson** [comment]
Works for me with
```
msbuild_path=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
msvs_version=2019
```
in .npmrc

**Comment by ranisalt** [comment]
@acceleratxr can you confirm @jeffrson suggestion?
