### ISSUE TITLE
0.25.0 is broken on MacOS

### ISSUE THREAD

**Issue by dacarley** [ranisalt/node-argon2#209]
Welcome to the issues section if it's your first time!

### Steps to reproduce
1. Create a blank node project via `npm init -y`
2. Add `argon2` via `npm i --save argon2`
3. Create an index.js file that consists of just the line `var argon2 = require("argon2");`
4. Run `node .`

### Expected behaviour
argon2 should be successfully installed by npm.
argon2 should be usable on MacOS

### Actual behaviour
npm produces on output when installing argon2 on MacOS:
```
npm i --save argon2

> argon2@0.25.0 install /private/tmp/foo/node_modules/argon2
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
[argon2] Success: "/private/tmp/foo/node_modules/argon2/lib/binding/argon2.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
```

argon2 cannot be loaded by Node on MacOS:
```
internal/modules/cjs/loader.js:977
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/private/tmp/foo/node_modules/argon2/lib/binding/argon2.node, 1): no suitable image found.  Did find:
	/private/tmp/foo/node_modules/argon2/lib/binding/argon2.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/private/tmp/foo/node_modules/argon2/lib/binding/argon2.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

### Environment
**Operating system**:
MacOS Mojave 10.14.6

**Node version:**
v12.9.1

**Comment by sethgoodluck** [comment]
Confirmed -- same issue here.

**Comment by ranisalt** [comment]
@hoangvvo maybe you can give a shot here as the only major update was moving to node-pre-gyp?

**Comment by pabricrui** [comment]
Same error here, 0.24.1 is working as expected.

Node version: 10.16.0
MacOs Mojave 10.14.5

**Comment by ranisalt** [comment]
Can either of you bisect to find in which commit the regression was introduced?

**Comment by dacarley** [comment]
I just tried this:

```
  "dependencies": {
    "argon2": "ranisalt/node-argon2"
  }
```

This causes npm to build the package from source:

```
➜  foo npm i

> argon2@0.25.0 install /private/tmp/foo/node_modules/argon2
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/ranisalt/node-argon2/releases/download/v0.25.0/argon2-v0.25.0-node-v72-darwin-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for argon2@0.25.0 and node@12.9.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
  CC(target) Release/obj.target/libargon2/argon2/src/opt.o
  CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
  CC(target) Release/obj.target/libargon2/argon2/src/core.o
  CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/libargon2/argon2/src/thread.o
  CC(target) Release/obj.target/libargon2/argon2/src/encoding.o
  LIBTOOL-STATIC Release/argon2.a
  CXX(target) Release/obj.target/argon2/src/argon2_node.o
  SOLINK_MODULE(target) Release/argon2.node
  COPY /private/tmp/foo/node_modules/argon2/lib/binding/argon2.node
  TOUCH Release/obj.target/action_after_build.stamp
npm WARN foo@1.0.0 No description
npm WARN foo@1.0.0 No repository field.

updated 1 package and audited 99 packages in 14.004s
found 0 vulnerabilities
```

Everything works correctly this way.

It appears that when it's installed via npm, it chooses the wrong prebuilt binaries.

**Comment by dacarley** [comment]
Perhaps the relevant clue is this:

`node-pre-gyp WARN Tried to download(404): https://github.com/ranisalt/node-argon2/releases/download/v0.25.0/argon2-v0.25.0-node-v72-darwin-x64-unknown.tar.gz`

**Comment by dacarley** [comment]
Anything I can do to help out here?

**Comment by pe8ter** [comment]
I compared the npm tarballs between argon2 versions 0.24.1 and 0.25.0, and noticed that the path to the prebuilt binaries are different. Notice how the path in latest version doesn't include any platform information:

* 0.24.1: _prebuilds/linux-x64/node.napi.node_
* 0.25.0: _lib/binding/argon2.node_

According to [node-pre-gyp's documentation](https://github.com/mapbox/node-pre-gyp#versioning), you can parameterize your _package.json_'s `binary.module_path` property [here](https://github.com/ranisalt/node-argon2/commit/fee5a25e25b4cda7c0236da83f0402e1e4683d99#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R45) in a manner similar to the previous version of argon2. Also you'll need to write the linux binary to that location.

**Comment by CyanoFresh** [comment]
0.25 also doesn't work on windows (almost same error)

**Comment by OneCent01** [comment]
Confirmed not working in Mac OS... This is a huge issue, guys. 

My error:
```
return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/ME/Desktop/obsidian-js/node_modules/argon2/lib/binding/argon2.node, 1): no suitable image found.  Did find:
	/Users/jpenney/Desktop/obsidian-js/node_modules/argon2/lib/binding/argon2.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/ME/Desktop/obsidian-js/node_modules/argon2/lib/binding/argon2.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:977:18)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/jpenney/Desktop/obsidian-js/node_modules/argon2/argon2.js:9:56)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
```

**Comment by hoangvvo** [comment]
@ranisalt The prebuilt is not uploaded properly (it's not there). Did you tag them? But I do not think Travis will do it properly either way.

I saw your #208 and it looks promising. I will try to look into that and help if that is possible.

**Comment by hoangvvo** [comment]
@ranisalt 
Oh, for some reason, you include a prebuild when publishing the package to npm. I don't think you should do that.

I think `node-gyp` assumes that is the build and use it regardless of platform.

https://cdn.jsdelivr.net/npm/argon2@0.25.0/lib/binding/

**Comment by ranisalt** [comment]
What should I do then? I did tag the commit, but when pushing it Github didn't get the tag (only my local repo is tagged), I'm unsure if that's a bug.

**Comment by hoangvvo** [comment]
@ranisalt Did you `git push` with `--tags`? If so, probably a bug.

Until we can do the TravisCI upload or #208 is merged, we need to temporary let the user rebuild from source.

If you have time, please deprecate v0.25.0 and publish v0.25.1 without the `/lib` folder.
(not related, but it's better to use [files](https://docs.npmjs.com/files/package.json#files) instead of `.gitignore` imo)

Sorry that my PR causes so much trouble 😢.

**Comment by hoangvvo** [comment]
Actually, let's try to use package.json's `files` before publishing 0.25.1 so that we don't accidently do this again. I will make a PR soon.

**Comment by gajus** [comment]
Is there a workaround?

**Comment by pe8ter** [comment]
@gajus Use v0.24.1.

**Comment by sethgoodluck** [comment]
Yep @pe8ter, 0.24.1 still works. 

If anyone newer to programming comes along, you can install the rollback version with one of the following commands :) 

`npm install argon2@0.24.1` or `yarn add argon2@0.24.1`

@ranisalt - anything any of us can do to help or good for now?

**Comment by ranisalt** [comment]
I don't know, Node/NPM environment is a mess, complete with tools deprecated for over 10 years, nonexistent prebuilding infrastructure and only recently got ABI stability. It hardly can get worse.

Anyway, I'll bump version in hopes it fixes this issue.

**Comment by hoangvvo** [comment]
@ranisalt Hey.. I recommend bumping the npm version and deprecate 0.25.0.

My PR at #215 will help greatly those who have trouble building (especially on Windows and Mac).
Or perhaps upload [these](https://github.com/hoangvvo/node-argon2/releases) to a 0.25.1 Github releases? (Not sure if it works this way)

Either way, try to bump the version when you have time.

**Comment by jaschaio** [comment]
None of the solutions worked for me.

Running `npm install argon2@0.24.1`:

```
> argon2@0.24.1 install /Applications/htdocs/project/node_modules/argon2
> node-gyp-build

  CC(target) Release/obj.target/libargon2/argon2/src/opt.o
  CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
  CC(target) Release/obj.target/libargon2/argon2/src/core.o
  CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/libargon2/argon2/src/thread.o
  CC(target) Release/obj.target/libargon2/argon2/src/encoding.o
  LIBTOOL-STATIC Release/argon2.a
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/argon2.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Jascha/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/Jascha/.nvm/versions/node/v12.11.1/bin/node" "/Users/Jascha/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Applications/htdocs/project/node_modules/argon2
gyp ERR! node -v v12.11.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm WARN node@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.24.1 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the argon2@0.24.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Jascha/.npm/_logs/2019-10-10T09_36_43_187Z-debug.log
```

Running `npm i ranisalt/node-argon2`:

```
npm WARN node@1.0.0 No repository field.

npm ERR! code EPERM
npm ERR! syscall spawn
npm ERR! errno EPERM
npm ERR! Error: spawn EPERM
npm ERR!     at ChildProcess.spawn (internal/child_process.js:394:11)
npm ERR!     at spawn (child_process.js:540:9)
npm ERR!     at execFile (child_process.js:224:17)
npm ERR!     at tryCatcher (/Users/Jascha/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm ERR!     at ret (eval at makeNodePromisifiedEval (/Users/Jascha/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:16:23)
npm ERR!     at opts.retry.retries (/Users/Jascha/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:192:14)
npm ERR!     at /Users/Jascha/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24
npm ERR!  OperationalError: spawn EPERM
npm ERR!     at ChildProcess.spawn (internal/child_process.js:394:11)
npm ERR!     at spawn (child_process.js:540:9)
npm ERR!     at execFile (child_process.js:224:17)
npm ERR!     at tryCatcher (/Users/Jascha/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm ERR!     at ret (eval at makeNodePromisifiedEval (/Users/Jascha/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:16:23)
npm ERR!     at opts.retry.retries (/Users/Jascha/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:192:14)
npm ERR!     at /Users/Jascha/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24 {
npm ERR!   cause: Error: spawn EPERM
npm ERR!       at ChildProcess.spawn (internal/child_process.js:394:11)
npm ERR!       at spawn (child_process.js:540:9)
npm ERR!       at execFile (child_process.js:224:17)
npm ERR!       at tryCatcher (/Users/Jascha/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm ERR!       at ret (eval at makeNodePromisifiedEval (/Users/Jascha/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:16:23)
npm ERR!       at opts.retry.retries (/Users/Jascha/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:192:14)
npm ERR!       at /Users/Jascha/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24 {
npm ERR!     errno: 'EPERM',
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'spawn'
npm ERR!   },
npm ERR!   stack: 'Error: spawn EPERM\n' +
npm ERR!     '    at ChildProcess.spawn (internal/child_process.js:394:11)\n' +
npm ERR!     '    at spawn (child_process.js:540:9)\n' +
npm ERR!     '    at execFile (child_process.js:224:17)\n' +
npm ERR!     '    at tryCatcher (/Users/Jascha/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)\n' +
npm ERR!     '    at ret (eval at makeNodePromisifiedEval (/Users/Jascha/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:16:23)\n' +
npm ERR!     '    at opts.retry.retries (/Users/Jascha/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:192:14)\n' +
npm ERR!     '    at /Users/Jascha/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24',
npm ERR!   errno: 'EPERM',
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'spawn',
npm ERR!   parent: 'node'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Jascha/.npm/_logs/2019-10-10T09_38_10_999Z-debug.log
```

Running as `sudo` makes no difference:

```
> argon2@0.25.1 install /Applications/htdocs/project/node_modules/argon2
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/ranisalt/node-argon2/releases/download/v0.25.1/argon2-v0.25.1-node-v72-darwin-x64-unknown.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for argon2@0.25.1 and node@12.11.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
  CC(target) Release/obj.target/libargon2/argon2/src/opt.o
  CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
  CC(target) Release/obj.target/libargon2/argon2/src/core.o
  CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/libargon2/argon2/src/thread.o
  CC(target) Release/obj.target/libargon2/argon2/src/encoding.o
  LIBTOOL-STATIC Release/argon2.a
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/argon2.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Jascha/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/Jascha/.nvm/versions/node/v12.11.1/bin/node" "/Users/Jascha/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Applications/htdocs/project/node_modules/argon2/lib/binding/argon2.node" "--module_name=argon2" "--module_path=/Applications/htdocs/project/node_modules/argon2/lib/binding" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Applications/htdocs/project/node_modules/argon2
gyp ERR! node -v v12.11.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/Jascha/.nvm/versions/node/v12.11.1/bin/node /Users/Jascha/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Applications/htdocs/project/node_modules/argon2/lib/binding/argon2.node --module_name=argon2 --module_path=/Applications/htdocs/project/node_modules/argon2/lib/binding --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Applications/htdocs/project/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/Users/Jascha/.nvm/versions/node/v12.11.1/bin/node" "/Applications/htdocs/project/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Applications/htdocs/project/node_modules/argon2
node-pre-gyp ERR! node -v v12.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 
Failed to execute '/Users/Jascha/.nvm/versions/node/v12.11.1/bin/node /Users/Jascha/.nvm/versions/node/v12.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Applications/htdocs/project/node_modules/argon2/lib/binding/argon2.node --module_name=argon2 --module_path=/Applications/htdocs/project/node_modules/argon2/lib/binding --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN node@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.25.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the argon2@0.25.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Jascha/.npm/_logs/2019-10-10T09_39_13_269Z-debug.log
```

**Comment by sethgoodluck** [comment]
> None of the solutions worked for me.
> 
> Running `npm install argon2@0.24.1`:

hmm, odd. Might be a cache/package lock issue. 
Go nuclear! 

1. Delete node_modules folder
2. Delete package-lock.json 
3. npm uninstall argon2 
4. npm install 
5. npm install @ version 0.24.1

Does that work?

**Comment by jaschaio** [comment]
Yes I actually tried that. I do get the same error. Lets see if the version bump resolves this

**Comment by hoangvvo** [comment]
@jaschaio Do you have GCC installed? https://github.com/ranisalt/node-argon2#before-installing

**Comment by jaschaio** [comment]
@hoangvvo thanks for the suggestion. I actually haven't had it installed, but now I do and running `CXX=g++-6 npm install argon2@0.24.1` still fails with the exact same error. `CXX=g++-6 npm install argon2` works, but then I get the original issue of `no suitable image found`.

**Comment by shaliniJK** [comment]
Was having the same issue with 0.25 on Mac Os. I tried 0.24 and it works.

**Comment by hoangvvo** [comment]
@jaschaio That is odd. What version of Node are you using?

**Comment by jaschaio** [comment]
Using `nvm`. Tried with node `8.14.0`, `10.15.3` and `12.11.1`

**Comment by jaschaio** [comment]
I got it working. I have MAMP installed and when executing `which libtool` it was displaying `/Applications/MAMP/Library/bin/libtool` instead of `/usr/bin/libtool`.

After removing some MAMP $path stuff from my `~/.bash_profile` and restarting the shell I was able to run `npm install argon2@0.24.1`

**Comment by pe8ter** [comment]
@ranisalt I confirmed `0.25.1` works on macOS.

**Comment by ranisalt** [comment]
Good to know!

**Comment by xdajay** [comment]
@ranisalt had same issue with latest version of argon 0.25.1 on Linux 64.
Solution by @sethgoodluck worked perfectly when installed an older version 0.24.1.

**Comment by bishoplee** [comment]
I resulted to using the version 0.24.1 and then it worked.
