### ISSUE TITLE
clang++ npm install argon2 - crashes because there is a space in the directory name (macos)

### ISSUE THREAD

**Issue by ahtremblay** [ranisalt/node-argon2#211]
```
CXX=clang++ npm install argon2

> argon2@0.24.1 install /Users/ahtremblay/Library/Mobile Documents/com~apple~CloudDocs/Files/Software/bitcorp2/bitcorp.node/node_modules/argon2
> node-gyp-build

  CC(target) Release/obj.target/libargon2/argon2/src/opt.o
  CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
  CC(target) Release/obj.target/libargon2/argon2/src/core.o
  CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/libargon2/argon2/src/thread.o
  CC(target) Release/obj.target/libargon2/argon2/src/encoding.o
  LIBTOOL-STATIC Release/argon2.a
  CXX(target) Release/obj.target/argon2/src/argon2_node.o
clang: error: no such file or directory: 'Documents/com~apple~CloudDocs/Files/Software/bitcorp2/bitcorp.node/node_modules/argon2/node_modules/node-addon-api'
make: *** [Release/obj.target/argon2/src/argon2_node.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/ahtremblay/Library/Mobile Documents/com~apple~CloudDocs/Files/Software/bitcorp2/bitcorp.node/node_modules/node-gyp/lib/build.js:190:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/ahtremblay/Library/Mobile Documents/com~apple~CloudDocs/Files/Software/bitcorp2/bitcorp.node/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ahtremblay/Library/Mobile Documents/com~apple~CloudDocs/Files/Software/bitcorp2/bitcorp.node/node_modules/argon2
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v5.0.1
gyp ERR! not ok 
npm WARN bitcorp.node@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.24.1 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the argon2@0.24.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ahtremblay/.npm/_logs/2019-10-05T13_18_34_391Z-debug.log

```

The reported error is:

`clang: error: no such file or directory: 'Documents/com~apple~CloudDocs/Files/Software/bitcorp2/bitcorp.node/node_modules/argon2/node_modules/node-addon-api'`

However, the directory does exist (inspection via Finder) but its actual name is

`/Users/ahtremblay/Library/Mobile Documents/com~apple~CloudDocs/Files/Software/bitcorp2/bitcorp.node/node_modules/node-addon-api`

The installer trims the directory structure before the first space. (There is a space between Mobile and Documents in the directory). 

Since this is the default directory for Icloud storage, it makes it unattractive to move my project to another directory.

**Comment by ahtremblay** [comment]
after some digging, it appears that this is a deep and ongoing issue (reported in 2004) with the dependencies of gyp. I resolved it by installing argon2 globally.

`npm install -g argon2`

**Comment by ranisalt** [comment]
> reported in 2004

Yet the Node committee can't decide moving on to a new build system because they can't choose one.
