### ISSUE TITLE
TypeError: pchstr must contain a $ as first char

### ISSUE THREAD

**Issue by AbderrazzakB** [ranisalt/node-argon2#221]
# Steps to reproduce
I'm trying to verify a password as described in the documentation.
The hash function works fine :  
passowrd: `r3a6xr5YMSBasZ6`  
hash: `$argon2i$v=19$m=4096,t=3,p=1$LRHUJo+J5tIP+OtWVclqRQ$AVCrpxOER8PtV7Pa4SoaJjIyREedI3VMIXKPeD8y7M4` 
### Expected behavior
Verify password
### Actual behavior
`TypeError: pchstr must contain a $ as first char
    at deserialize (/home/abderrazzak/Lab/projects/safir/node_modules/@phc/format/index.js:138:11)
    at Object.verify (/home/abderrazzak/Lab/projects/safir/node_modules/argon2/argon2.js:55:73)
    at model.userSchema.methods.comparePassword (/home/abderrazzak/Lab/projects/safir/build/models/user.js:91:19)
    at Function.userSchema.statics.getAuthenticated (/home/abderrazzak/Lab/projects/safir/build/models/user.js:150:27)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)`
### Environment
**Operating system**:
Archlinux GNOME v3.34.0
**Node version:**
v11.15.0
**Compiler version:**
v9.2.0

**Comment by ranisalt** [comment]
I guess you're swapping argument order. Hash comes first, plain password comes second.
```js
> await argon2.verify('$argon2i$v=19$m=4096,t=3,p=1$LRHUJo+J5tIP+OtWVclqRQ$AVCrpxOER8PtV7Pa4SoaJjIyREedI3VMIXKPeD8y7M4', 'r3a6xr5YMSBasZ6')
true
```

**Comment by AbderrazzakB** [comment]
Thank you, I did swap the order of the arguments.
