### ISSUE TITLE
0.25.x does not build on MacOS

### ISSUE THREAD

**Issue by jnardone** [ranisalt/node-argon2#230]
### Before creating an issue, please be sure to:
- [ ] Checkout to the latest version, **including submodules**
- [ ] Try to find an *isolated* way to reproduce the behavior
- [ ] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1.  Specify 0.25.1 in package.json
2. npm i

### Expected behaviour
Argon2 should build.  0.24.1 works.

### Actual behaviour

Fails, likely due to: https://github.com/nodejs/node-gyp/issues/1917
and https://github.com/npm/cli/issues/287 but who knows when they will get their act together.

**Have you given any thought to publishing pre-built binaries for common OSes?**

```
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/ranisalt/node-argon2/releases/download/v0.25.1/argon2-v0.25.1-node-v72-darwin-x64-unknown.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for argon2@0.25.1 and node@12.13.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
Traceback (most recent call last):
  File "/Users/joe/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "/Users/joe/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "/Users/joe/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "/Users/joe/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/joe/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2215, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/Users/joe/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 802, in Write
    self.WriteCopies(spec['copies'], extra_outputs, part_of_all)
  File "/Users/joe/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1145, in WriteCopies
    env = self.GetSortedXcodeEnv()
  File "/Users/joe/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1885, in GetSortedXcodeEnv
    additional_settings)
  File "/Users/joe/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1616, in GetSortedXcodeEnv
    additional_settings)
  File "/Users/joe/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1527, in _GetXcodeEnv
    if XcodeVersion() >= '0500' and not env.get('SDKROOT'):
TypeError: '>=' not supported between instances of 'tuple' and 'str'
```

### Environment
**Operating system**:
macOS Mojave 10.14.6

**Node version:**
Node 12.13.0

**Compiler version:**
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by ranisalt** [comment]
> **Have you given any thought to publishing pre-built binaries for common OSes?**

Yes, and it is a pain in the ass. Feel free to help, but I can't give enough time for it to work properly. @hoangvvo did a lot recently in that direction.

**Comment by jnardone** [comment]
That's too bad. :( The ecosystem issues around node-gyp and macos will keep us pinned then on 0.24.1.

**Comment by ranisalt** [comment]
> The ecosystem issues around node-gyp

Considering that when Node adopted gyp it was already being deprecated, yes, it is a shame :/ I hope we can change things soon, though!

**Comment by jnardone** [comment]
For the time being; 0.26.0 did indeed install correctly on MacOS :)

**Comment by ranisalt** [comment]
Yay! Kudos to @BjornLuG for the PR and all others that tried and helped :)

**Comment by jnardone** [comment]
it's not all good news.  bug report incoming w issues on Debian.

**Comment by ranisalt** [comment]
You shouldn't make me sad again that fast.
