### ISSUE TITLE
Build Fails on Raspbian

### ISSUE THREAD

**Issue by Pecacheu** [ranisalt/node-argon2#290]
Just trying to install with `npm install argon2`

```
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/ranisalt/node-argon2/releases/download/v0.27.2/argon2-v0.27.2-napi-v3-linux-arm-glibc.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for argon2@0.27.2 and node@12.18.4 (node-v72 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/ranisalt/node-argon2/releases/download/v0.27.2/argon2-v0.27.2-napi-v3-linux-arm-glibc.tar.gz
gyp WARN EACCES current user ("pi") does not have permission to access the dev dir "/root/.cache/node-gyp/12.18.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/server/node_modules/argon2/.node-gyp"
make: Entering directory '/home/server/node_modules/argon2/build'
make: *** No rule to make target '../.node-gyp/12.18.4/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/home/server/node_modules/argon2/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.10.11-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/server/node_modules/argon2/lib/binding/napi-v3/argon2.node" "--module_name=argon2" "--module_path=/home/server/node_modules/argon2/lib/binding/napi-v3" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /home/server/node_modules/argon2
gyp ERR! node -v v12.18.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/server/node_modules/argon2/lib/binding/napi-v3/argon2.node --module_name=argon2 --module_path=/home/server/node_modules/argon2/lib/binding/napi-v3 --napi_version=6 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm WARN enoent ENOENT: no such file or directory, open '/home/server/package.json'
npm WARN Server No description
npm WARN Server No repository field.
npm WARN Server No README data
npm WARN Server No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.27.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the argon2@0.27.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-07T20_44_35_777Z-debug.log
```

**Operating system**:
Operating System: Raspbian GNU/Linux 10 (buster)
Kernel: Linux 5.10.11-v7+
Architecture: armv7l

**Node version:**
v12.18.4

**Compiler version:**
gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1)

**Comment by Pecacheu** [comment]
Whoops, rookie Linux mistake: Didn't try running with `sudo`!

**Comment by ranisalt** [comment]
> Whoops, rookie Linux mistake: Didn't try running with `sudo`!

A rookie mistake is to run everything as the super user. Don't do it.

**Comment by Pecacheu** [comment]
Well fortunately I only had to run as sudo to install. My actual node.js script is running without sudo fine, though.
