### ISSUE TITLE
Error Building for Docker

### ISSUE THREAD

**Issue by faridg18** [ranisalt/node-argon2#321]
Welcome to the issues section if it's your first time!

### Before creating an issue, please be sure to:
- [*] Checkout to the latest version, **including submodules**
- [*] Try to find an *isolated* way to reproduce the behavior
- [*] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1.  I have a Docker file with the following configuration
``` 
FROM node:14-slim
WORKDIR /usr/src/app

RUN apt update && apt install python -y
RUN apt install build-essential -y
RUN apt install gcc

RUN npm install -g node-gyp

COPY package.json ./

RUN npm install

RUN npm install argon2 --save --target=14.2.0 --target_arch=x64 --target_platform=linux --target_libc=glibc

COPY . .

EXPOSE 3000
CMD [ "node", "app.js" ]
```
2. Run and build the file

### Expected behaviour
Expected To compile

### Actual behaviour
I get this result

```sh
internal/modules/cjs/loader.js:1144
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/src/app/node_modules/argon2/lib/binding/napi-v3/argon2.node: invalid ELF header
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/usr/src/app/node_modules/argon2/argon2.js:9:56)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/usr/src/app/handlers/auth.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_DLOPEN_FAILED'
}

```

### Environment
**Operating system**: Docker on macOS Catalina

**Node version:**
14
**Compiler version:**

**Comment by sangdth** [comment]
I'm facing similar error message. The Dockerfile:

```
FROM ubuntu:22.04

WORKDIR /app/myapp

RUN apt-get update --yes
RUN apt-get install curl --yes
RUN curl --silent --location https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get install gcc build-essential nodejs --yes

RUN npm install -g node-gyp

COPY package*.json ./

RUN npm install
RUN npm install argon2

COPY . .

CMD ["npm","run","dev"]
```
Please help.

**Comment by ranisalt** [comment]
@sangdth ate you by any chance installing modules locally (i.e. ran `npm install` outside the container) and then copied it in? Try removing `node_modules` before building your container.

**Comment by sangdth** [comment]
Thanks @ranisalt, I managed to get different error message (little progress, yay!), so I will open new issue.
