### ISSUE TITLE
argon2 rebuild failed

### ISSUE THREAD

**Issue by wahyuhenditya** [ranisalt/node-argon2#331]
Welcome to the issues section if it's your first time!

### Before creating an issue, please be sure to:
- [x] Checkout to the latest version, **including submodules**
- [x] Try to find an *isolated* way to reproduce the behavior
- [x] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1. Installing Directus using docker
2. NPM installation run successfully 
3. Running `npm rebuild argon2 --build-from-source` then get error

### Expected behaviour
Running `npm rebuild argon2 --build-from-source` shouldn't shown error, have done this before but suddenly today getting this error

### Actual behaviour
Getting this error on docker installation
```
RUN npm rebuild argon2 --build-from-source
 ---> Running in d42a37835144
> argon2@0.28.3 install /app/node_modules/argon2
> node-pre-gyp install --fallback-to-build
make: Entering directory '/app/node_modules/argon2/build'
  CC(target) Release/obj.target/libargon2/argon2/src/opt.o
  CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
  CC(target) Release/obj.target/libargon2/argon2/src/core.o
  CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/libargon2/argon2/src/thread.o
  CC(target) Release/obj.target/libargon2/argon2/src/encoding.o
  AR(target) Release/obj.target/argon2.a
  COPY Release/argon2.a
  CXX(target) Release/obj.target/argon2/src/argon2_node.o
../src/argon2_node.cpp: In function 'argon2_context {anonymous}::make_context(uint8_t*, {anonymous}::ustring&, {anonymous}::ustring&, {anonymous}::Options&)':
../src/argon2_node.cpp:52:25: error: invalid conversion from 'const unsigned char*' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
     ctx.pwd = plain.data();
               ~~~~~~~~~~^~
../src/argon2_node.cpp:54:25: error: invalid conversion from 'const unsigned char*' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
     ctx.salt = salt.data();
                ~~~~~~~~~^~
../src/argon2_node.cpp:56:38: error: invalid conversion from 'const unsigned char*' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
     ctx.secret = opts.secret.empty() ? nullptr : opts.secret.data();
                  ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/argon2_node.cpp:58:30: error: invalid conversion from 'const unsigned char*' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
     ctx.ad = opts.ad.empty() ? nullptr : opts.ad.data();
              ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Release/obj.target/argon2/src/argon2_node.o] Error 1
argon2.target.mk:124: recipe for target 'Release/obj.target/argon2/src/argon2_node.o' failed
make: Leaving directory '/app/node_modules/argon2/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Linux 5.4.0-89-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/app/node_modules/argon2/lib/binding/napi-v3/argon2.node" "--module_name=argon2" "--module_path=/app/node_modules/argon2/lib/binding/napi-v3" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /app/node_modules/argon2
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/app/node_modules/argon2/lib/binding/napi-v3/argon2.node --module_name=argon2 --module_path=/app/node_modules/argon2/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/app/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
node-pre-gyp ERR! System Linux 5.4.0-89-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /app/node_modules/argon2
node-pre-gyp ERR! node -v v14.18.1
node-pre-gyp ERR! node-pre-gyp -v v1.0.7
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/app/node_modules/argon2/lib/binding/napi-v3/argon2.node --module_name=argon2 --module_path=/app/node_modules/argon2/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.28.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the argon2@0.28.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-03T04_53_06_272Z-debug.log
```

### Environment
**Operating system**: 
Linux
**Node version:** 
Node 14
**Compiler version:**
N/A

**Comment by wahyuhenditya** [comment]
Apparently this issue can be fixed by installing older version of argon2 using such command
`npm rebuild argon2@0.28.2 --build-from-source`

**Comment by federicocappellotto97** [comment]
> Apparently this issue can be fixed by installing older version of argon2 using such command
> `npm rebuild argon2@0.28.2 --build-from-source`

This is not working for me

**Comment by perry-mitchell** [comment]
@wahyuhenditya Why did you close this? It's obviously still an issue..

**Comment by perry-mitchell** [comment]
@ranisalt Any idea what's happening here? The rebuild command was working in 0.28.2 for me, but fails in 0.28.3.

**Comment by wahyuhenditya** [comment]
> @wahyuhenditya Why did you close this? It's obviously still an issue..
> 
> @federicocappellotto97 Make sure to peg your version at `0.28.2`, not `^0.28.2`, otherwise the issue will persist.

@perry-mitchell I closed this issue because I already found the workaround for this issue as I mentioned in the comment before, and this issue also has been raised by others and the one that mentioned directus also has been raised with notes from the contributor of directus #328
