### ISSUE TITLE
Build for WASM

### ISSUE THREAD

**Issue by GauBen** [ranisalt/node-argon2#375]
Hey! I'd like to use argon2 in [stackblitz.com](https://stackblitz.com/)'s WebContainers for educational purposes. This is not currently possible because argon2 does not ship a WASM binary.

```console
~/app
❯ node
Welcome to Node.js v16.14.2.
Type ".help" for more information.
> const argon2 = require('argon2');
Uncaught:
Error: Cannot find module '/home/app/node_modules/argon2/lib/binding/napi-v3/argon2.node'
Require stack:
- /home/app/node_modules/argon2/argon2.js
- <repl>
    at InternalError (https://httplocalhost5173-ygzs-pk6i28nn.w-corp.staticblitz.com/blitz.bc9c2adb.js:35:344094)
    at Module._resolveFilename (https://httplocalhost5173-ygzs-pk6i28nn.w-corp.staticblitz.com/blitz.bc9c2adb.js:35:242305)
    at Module._load (https://httplocalhost5173-ygzs-pk6i28nn.w-corp.staticblitz.com/blitz.bc9c2adb.js:35:239836)
    at Module.prototype.require (https://httplocalhost5173-ygzs-pk6i28nn.w-corp.staticblitz.com/blitz.bc9c2adb.js:35:243084)
    at i (https://httplocalhost5173-ygzs-pk6i28nn.w-corp.staticblitz.com/blitz.bc9c2adb.js:35:480348)
    at _0x2ddf94 (https://httplocalhost5173-ygzs-pk6i28nn.w-corp.staticblitz.com/blitz.bc9c2adb.js:44:143940)
    at <anonymous> (/home/app/node_modules/argon2/argon2.js:9:32)
```

Would it be possible to add a WASM build to the package?

**Comment by ranisalt** [comment]
You can use [argon2-browser](https://github.com/antelle/argon2-browser) for that purpose

**Comment by GauBen** [comment]
Works like a charm, thanks for quick you answer!
