### ISSUE TITLE
Install fails on macOS 13 with Node 18

### ISSUE THREAD

**Issue by realandrew** [ranisalt/node-argon2#379]
### Steps to reproduce
1. Try to install argon2 via `npm install argon2` or `yarn add argon2` on a system with pre-built binaries using Node v18.

### Expected behaviour
Argon2 installs successfully.

### Actual behaviour
Argon2 fails to install with error code `ERR_REQUIRE_ESM`. Error log looks like:
```
user@Users-Mini project % npm install argon2
npm ERR! code 1
npm ERR! path /Users/user/Projects/Web/project/node_modules/argon2
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! /Users/user/Projects/Web/project/node_modules/gauge/wide-truncate.js:3
npm ERR! var stripAnsi = require('strip-ansi')
npm ERR!                 ^
npm ERR! 
npm ERR! Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/user/Projects/Web/project/node_modules/strip-ansi/index.js from /Users/user/Projects/Web/project/node_modules/gauge/wide-truncate.js not supported.
npm ERR! Instead change the require of index.js in /Users/user/Projects/Web/project/node_modules/gauge/wide-truncate.js to a dynamic import() which is available in all CommonJS modules.
npm ERR!     at Object.<anonymous> (/Users/user/Projects/Web/project/node_modules/gauge/wide-truncate.js:3:17)
npm ERR!     at Object.<anonymous> (/Users/user/Projects/Web/project/node_modules/gauge/render-template.js:4:20)
npm ERR!     at Object.<anonymous> (/Users/user/Projects/Web/project/node_modules/gauge/plumbing.js:3:22)
npm ERR!     at Object.<anonymous> (/Users/user/Projects/Web/project/node_modules/gauge/index.js:2:16)
npm ERR!     at Object.<anonymous> (/Users/user/Projects/Web/project/node_modules/npmlog/log.js:3:13)
npm ERR!     at Object.<anonymous> (/Users/user/Projects/Web/project/node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js:23:13)
npm ERR!     at Object.<anonymous> (/Users/user/Projects/Web/project/node_modules/@mapbox/node-pre-gyp/lib/main.js:9:22)
npm ERR!     at Object.<anonymous> (/Users/user/Projects/Web/project/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp:4:1) {
npm ERR!   code: 'ERR_REQUIRE_ESM'
npm ERR! }
npm ERR! 
npm ERR! Node.js v18.16.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2023-06-09T03_49_09_909Z-debug-0.log
```

### Environment
**Operating system**: macOS Ventura 13.4

**Node version:** v18.16.0

**Compiler version:** NA

**Comment by ranisalt** [comment]
This seems to be a bug in `gauge` instead. Does it happen with other Node versions? (as you emphasized that you are on v18)

**Comment by realandrew** [comment]
It also happens with Node 16 and 14. I think this is a conflict with another dependency, I just created a fresh project with no dependencies and argon2 installs fine there on Node 18, I'll close this issue.
