### ISSUE TITLE
Error: No native build was found for platform=linux arch=x64 runtime=node abi=115 uv=1 libc=glibc node=20.17.0

### ISSUE THREAD

**Issue by Arhyel24** [ranisalt/node-argon2#421]
Error: No native build was found for platform=linux arch=x64 runtime=node abi=115 uv=1 libc=glibc node=20.17.0
    loaded from: /var/task/node_modules/argon2

    at load.resolve.load.path (/var/task/node_modules/node-gyp-build/node-gyp-build.js:60:9)
    at load (/var/task/node_modules/node-gyp-build/node-gyp-build.js:22:30)
    at Object.<anonymous> (/var/task/node_modules/argon2/argon2.cjs:7:32)
    at Module.<anonymous> (/opt/rust/bytecode.js:1:1435)
    at l._compile (/opt/rust/bytecode.js:1:3140)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at /opt/rust/nodejs.js:1:11762
    at Function.dr (/opt/rust/nodejs.js:1:12136) {
  page: '/'
}

**Comment by shreecodes** [comment]
We are also seeing this issue for argon2@0.41.1, upon deploying to Vercel.

There is an open discussion here, and folks suggest downgrading to v0.31.2: https://github.com/vercel/next.js/discussions/65978

**Comment by ranisalt** [comment]
Please follow the issue template, I need more info about your system to investigate

**Comment by Arhyel24** [comment]
I am facing this issue when deploying to vercel.

**Comment by NotSimple** [comment]
I'm also seeing this issue when deploying to AWS Lambda functions

**Comment by ranisalt** [comment]
Thanks, I'll try to reproduce it in Vercel first to start investigating

**Comment by NotSimple** [comment]
I've confirmed this is a downstream error in my case. I am deploying Next.js to AWS using [OpenNext](https://github.com/opennextjs/opennextjs-aws) and it wasn't properly copying the prebuilt binaries. I manually copied the binaries before deploying and it works now.

Also, for anyone using Next.js, their build step uses the vercel nft library which was [having trouble with prebuilt binaries](https://github.com/vercel/nft/issues/391) in the past. This is already fixed in theory, but older next.js versions might not have the latest nft dependency (and even the latest stable next.js release isn't using the latest nft version).

**Comment by ranisalt** [comment]
In this case, make sure you have Next 14.2.0 or newer installed, as that version ships with their fix.

**Comment by newarifrh** [comment]
i faced the issue on next.js 12.2.14, but it was resolved by including prebuilds via the following code in `next.config.js`

```
const OPTIMIZE_OUTPUT = true;

const nextConfig = {
  ...(OPTIMIZE_OUTPUT && {
    output: "standalone",
  }),
  experimental: {
    outputFileTracingIncludes: {
      "/": ["./node_modules/argon2/prebuilds/*/*.node"],   <------- the savior
    },
  },
};
```

**Comment by Arhyel24** [comment]
Thanks guys, my issue has been resolved.

**Comment by wmtrinu** [comment]
Having this issue as well when deploying to AWS Lambda

`No native build was found for platform=linux arch=x64 runtime=node abi=115 uv=1 libc=glibc node=20.17.0`

```
"Error: No native build was found for platform=linux arch=x64 runtime=node abi=115 uv=1 libc=glibc node=20.17.0",
        "    loaded from: /var/task/src",
        "",
        "    at Function.load.resolve.load.path (/node_modules/node-gyp-build/node-gyp-build.js:60:9)",
        "    at load (/node_modules/node-gyp-build/node-gyp-build.js:22:30)",
        "    at ../../node_modules/argon2/argon2.cjs (/node_modules/argon2/argon2.cjs:7:32)",
        "    at __require (/var/task/src/server.js:9:50)",
        "    at Object.<anonymous> (/src/router.ts:6:22)",
        "    at Module._compile (node:internal/modules/cjs/loader:1469:14)",
        "    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)",
        "    at Module.load (node:internal/modules/cjs/loader:1288:32)",
        "    at Module._load (node:internal/modules/cjs/loader:1104:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1311:19)"
```

I'm using a monorepo setup with trpc with node runtime `20.x`

**Comment by juanmguzmann** [comment]
hey @wmtrinu could you sort this out? I am also running argon2 in a lambda using a monorepo and facing the same issue

**Comment by ranisalt** [comment]
@juanmguzmann you should raise it upstream in Next.js as the issue is there. You can find workarounds in the pages linked here, but it seems to be inconsistent.

**Comment by juanmguzmann** [comment]
@ranisalt I am not using it with nextjs, but in a lambda. I am working with the SST framework. When I invoke a lambda that imports that dependency I get this error: ` No native build was found for platform=darwin arch=arm64 runtime=node abi=115 uv=1 armv=8 libc=glibc node=20.11.0`

**Comment by trinu-admin** [comment]
> hey @wmtrinu could you sort this out? I am also running argon2 in a lambda using a monorepo and facing the same issue

I haven't, I'm currently working on another project but this is still happening on AWS Lambda @juanmguzmann

**Comment by notsimple** [comment]
@juanmguzmann if you‘re deploying a lambda with SST, it’s still an upstream config issue. There‘s an option to directly install dependencies (which will include the binary). Checkout the nodejs option in the official docs: https://sst.dev/docs/component/aws/function

**Comment by owlyowl** [comment]
I'm trying to get this working again when deploying to a Lamda in CDK.

I'm trying to get this working with CDK I've copied pre-builts via a node script into a layer but alas:
![image](https://github.com/user-attachments/assets/459eeb79-cfaf-42af-b907-861443263aae)

![image](https://github.com/user-attachments/assets/eab944ce-cba3-400e-887d-0cc56ee44ce4)

Neither of these approaches seem to work I'm getting:
```
    "errorType": "Error",
    "errorMessage": "No native build was found for platform=linux arch=x64 runtime=node abi=115 uv=1 libc=glibc node=20.18.0\n    loaded from: /var/task\n",
    "stack": [
        "Error: No native build was found for platform=linux arch=x64 runtime=node abi=115 uv=1 libc=glibc node=20.18.0",
        "    loaded from: /var/task",
```

I'll keep digging but I'd be keen to know what others have been doing?
